name: Build for prod and commit

on:
  push:
    branches: [gh-pages]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Build with prod settings
        run: npm run build-prod

      - name: Copy custom 404 page for GitHub pages
        run: cp ${GITHUB_WORKSPACE}/src/404.html ${GITHUB_WORKSPACE}/docs/404.html

      - name: Update last deployment data and time
        run: sed -i "s/DD-MM-YYYY HH:MM:SS/$(date +'%d-%m-%Y %H:%M:%S')/g" ${GITHUB_WORKSPACE}/docs/assets/status.json

      - name: Commit prod artifacts
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Szymon Gross
          author_email: szyg@netcompany.com
          message: 'Added built artifacts for GitHub pages'
          add: 'docs --force'
