name: Build and test

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build
        run: |
          npm install
          npm run build-prod

      - name: Commit
        run: |
          git add docs
          git commit -m 'CI - prod deploy'
          git push
